server:
  port: 9001

spring:
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:file:./data/plugins-db;AUTO_SERVER=TRUE;
    driver-class-name: org.h2.Driver
    username: plugin
    password: plugin
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect

plugins:
  path: ./plugins-store/