server:
  port: 9001

eureka:
  server:
    eviction-interval-timer-in-ms: 5000 #default 60000
    response-cache-update-interval-ms: 1000 #default 30000
  instance:
    health-check-url: https://${eureka.hostname}/actuator/health
  client:
    healthcheck:
      enabled: true
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://localhost:9001/eureka/

spring:
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:file:./data/plugins-db
    driver-class-name: org.h2.Driver
    username: plugin
    password: plugin
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect

plugins:
  path: ./plugins-store/