version: '2'

services:

  rabbitmq:
    image: "rabbitmq:3.8.3-management"
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: tianguix
      RABBITMQ_DEFAULT_PASS: tianguix