spring:
  application:
    name: order-manager
eureka:
  instance:
    instance-id: ${spring.application.name}-${server.port}
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://localhost:9001/eureka/
    healthcheck:
      enabled: true
server:
  port: 9002

management:
  endpoint:
    shutdown:
      enabled: true
  endpoints:
    web:
      exposure:
        include: '*'